/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AccountInfo.java
 *
 * Created on Jan 10, 2013, 8:09:46 PM
 */
package batapos;

import Login.CurrentUser;

/**
 *
 * @author Asadul
 */
public class AccountInfo extends javax.swing.JFrame {
CurrentUser ob;

    public void setOb(CurrentUser ob) {
        this.ob = ob;
    }
    

   

    

    /** Creates new form AccountInfo */
    public AccountInfo() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountInfoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        uIdTextField = new javax.swing.JTextField();
        eNameTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        eAddressTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        eShowButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        eDesignationTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        eContactTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        eEmailTextField = new javax.swing.JTextField();
        eEditButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Account Info");

        accountInfoPanel.setBackground(new java.awt.Color(255, 255, 255));
        accountInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Account Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 1, 24), new java.awt.Color(255, 0, 51))); // NOI18N
        accountInfoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18));
        jLabel1.setText("User Id:");
        accountInfoPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 130, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 18));
        jLabel3.setText("Employee name:");
        accountInfoPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        uIdTextField.setEditable(false);
        accountInfoPanel.add(uIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 200, -1));

        eNameTextField.setEditable(false);
        accountInfoPanel.add(eNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 200, -1));
        accountInfoPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 290, 40));

        eAddressTextField.setEditable(false);
        accountInfoPanel.add(eAddressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 200, -1));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 18));
        jLabel2.setText("Address");
        accountInfoPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 130, -1));

        eShowButton.setBackground(new java.awt.Color(102, 153, 255));
        eShowButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        eShowButton.setText("Show");
        eShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eShowButtonActionPerformed(evt);
            }
        });
        accountInfoPanel.add(eShowButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, -1));

        backButton.setBackground(new java.awt.Color(102, 153, 255));
        backButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        accountInfoPanel.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, -1, -1));

        eDesignationTextField.setEditable(false);
        accountInfoPanel.add(eDesignationTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 200, -1));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 18));
        jLabel4.setText("Designation");
        accountInfoPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        eContactTextField.setEditable(false);
        accountInfoPanel.add(eContactTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 200, -1));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 18));
        jLabel6.setText("Contact:");
        accountInfoPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 18));
        jLabel5.setText("E-mail");
        accountInfoPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 130, -1));

        eEmailTextField.setEditable(false);
        accountInfoPanel.add(eEmailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 200, -1));

        eEditButton1.setBackground(new java.awt.Color(102, 153, 255));
        eEditButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        eEditButton1.setText("Edit");
        eEditButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eEditButton1ActionPerformed(evt);
            }
        });
        accountInfoPanel.add(eEditButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(397, 397, 397)
                .addComponent(accountInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(434, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(accountInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
// TODO add your handling code here:
    ManagerView aManagerView=new ManagerView();
    this.setVisible(false);
    aManagerView.setVisible(true);
}//GEN-LAST:event_backButtonActionPerformed

    private void eShowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eShowButtonActionPerformed
        // TODO add your handling code here:
        CurrentUser aCurrentUser = null;
        if (ob != null) {
            aCurrentUser = (CurrentUser) ob;
        }
        uIdTextField.setText(aCurrentUser.getUserId());
        eNameTextField.setText(aCurrentUser.getEmployeeName());
        eDesignationTextField.setText(aCurrentUser.getDesignation());
        eContactTextField.setText(aCurrentUser.getContact());
        eAddressTextField.setText(aCurrentUser.getAddress());
        eEmailTextField.setText(aCurrentUser.getEmail());
    }//GEN-LAST:event_eShowButtonActionPerformed

    private void eEditButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eEditButton1ActionPerformed
        // TODO add your handling code here:
        CurrentUser aCurrentUser = null;
        if (ob != null) {
            aCurrentUser = (CurrentUser) ob;
        }
        AccountEdit aAccountEdit =new  AccountEdit();
        this.setVisible(false);
        aAccountEdit.setVisible(true);
    }//GEN-LAST:event_eEditButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AccountInfo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accountInfoPanel;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField eAddressTextField;
    private javax.swing.JTextField eContactTextField;
    private javax.swing.JTextField eDesignationTextField;
    private javax.swing.JButton eEditButton1;
    private javax.swing.JTextField eEmailTextField;
    private javax.swing.JTextField eNameTextField;
    private javax.swing.JButton eShowButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField uIdTextField;
    // End of variables declaration//GEN-END:variables
}
