/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AccountEdit.java
 *
 * Created on Jan 10, 2013, 8:26:24 PM
 */
package batapos;

import Login.CurrentUser;
import Manager.AddressEdit;
import Manager.ContactEdit;
import Manager.EmailEdit;
import Manager.NameEdit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Asadul
 */
public class AccountEdit extends javax.swing.JFrame {


    /** Creates new form AccountEdit */
    public AccountEdit() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        editAccountInfoPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        eOkButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        emailRadioButton = new javax.swing.JRadioButton();
        nameRadioButton = new javax.swing.JRadioButton();
        addressRadioButton = new javax.swing.JRadioButton();
        contactRadioButton = new javax.swing.JRadioButton();
        infoTextField = new javax.swing.JTextField();
        backButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Account Edit");

        editAccountInfoPanel.setBackground(new java.awt.Color(204, 204, 204));
        editAccountInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Edit Account Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 1, 24), new java.awt.Color(255, 0, 51))); // NOI18N
        editAccountInfoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 18));
        jLabel3.setText("Select editable component");
        editAccountInfoPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));
        editAccountInfoPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 290, 40));

        eOkButton.setBackground(new java.awt.Color(102, 153, 255));
        eOkButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        eOkButton.setText("OK");
        eOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eOkButtonActionPerformed(evt);
            }
        });
        editAccountInfoPanel.add(eOkButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, -1));

        logoutButton.setBackground(new java.awt.Color(102, 153, 255));
        logoutButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        editAccountInfoPanel.add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 18));
        jLabel6.setText("Enter new info");
        editAccountInfoPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        emailRadioButton.setFont(new java.awt.Font("Sylfaen", 1, 11));
        emailRadioButton.setText("E-mail");
        editAccountInfoPanel.add(emailRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 70, -1));

        nameRadioButton.setFont(new java.awt.Font("Sylfaen", 1, 11));
        nameRadioButton.setText("Name");
        editAccountInfoPanel.add(nameRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 70, -1));

        addressRadioButton.setFont(new java.awt.Font("Sylfaen", 1, 11));
        addressRadioButton.setText("Adress");
        editAccountInfoPanel.add(addressRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 70, -1));

        contactRadioButton.setFont(new java.awt.Font("Sylfaen", 1, 11));
        contactRadioButton.setText("Contact");
        editAccountInfoPanel.add(contactRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));
        editAccountInfoPanel.add(infoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 190, 30));

        backButton1.setBackground(new java.awt.Color(102, 153, 255));
        backButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        backButton1.setText("Back");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });
        editAccountInfoPanel.add(backButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(442, Short.MAX_VALUE)
                .addComponent(editAccountInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(389, 389, 389))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(editAccountInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
// TODO add your handling code here:
    PosLogin aPosLogin = new PosLogin();
    this.setVisible(false);
    aPosLogin.setVisible(true);
}//GEN-LAST:event_logoutButtonActionPerformed

    private void eOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eOkButtonActionPerformed
        // TODO add your handling code here:
        if(!infoTextField.getText().isEmpty()){
        if(nameRadioButton.isSelected()){
            NameEdit aNameEdit =new NameEdit();
            try {
                if(aNameEdit.updateName(infoTextField.getText())){
                    JOptionPane.showMessageDialog(null, "Please logout and then login to make the change ");
                }
            } catch (SQLException ex) {
                Logger.getLogger(AccountEdit.class.getName()).log(Level.SEVERE, null, ex);
            }
       }
        
        else if(addressRadioButton.isSelected()){
            AddressEdit aAddressEdit =new AddressEdit();
            try {
                if(aAddressEdit.updateAddress(infoTextField.getText())){
                    JOptionPane.showMessageDialog(null, "Please logout and then login to make the change ");
                }
            } catch (SQLException ex) {
                Logger.getLogger(AccountEdit.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(contactRadioButton.isSelected()){
            ContactEdit aContactEdit =new ContactEdit();
            try {
                if(aContactEdit.updateContact(infoTextField.getText())){
                   JOptionPane.showMessageDialog(null, "Please logout and then login to make the change "); 
                }
            } catch (SQLException ex) {
                Logger.getLogger(AccountEdit.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(emailRadioButton.isSelected()){
            EmailEdit aEmailEdit = new  EmailEdit();
            try {
                if(aEmailEdit.updateEmail(infoTextField.getText())){
                    JOptionPane.showMessageDialog(null, "Please logout and then login to make the change "); 
                }
            } catch (SQLException ex) {
                Logger.getLogger(AccountEdit.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Please select editable option!!!");
        }
        else
            JOptionPane.showMessageDialog(null, "Please enter the info!!!");
    }//GEN-LAST:event_eOkButtonActionPerformed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        // TODO add your handling code here:
        ManagerView aManagerView =new ManagerView();
        this.setVisible(false);
        aManagerView.setVisible(true);
    }//GEN-LAST:event_backButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AccountEdit().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton addressRadioButton;
    private javax.swing.JButton backButton1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton contactRadioButton;
    private javax.swing.JButton eOkButton;
    private javax.swing.JPanel editAccountInfoPanel;
    private javax.swing.JRadioButton emailRadioButton;
    private javax.swing.JTextField infoTextField;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JRadioButton nameRadioButton;
    // End of variables declaration//GEN-END:variables
}
