/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CashierView.java
 *
 * Created on Jan 4, 2013, 1:08:56 AM
 */
package batapos;

import Login.CurrentUser;
import Login.CurrentUserList;
import Login.Login;
import Transaction.UpdateInventory;
import Product.SearchByCategory;
import Product.SearchById;
import Product.SearchByName;
import Transaction.Cart;
import Transaction.CartList;
import Transaction.CreateTransaction;
import Transaction.SelectProduct;
import com.sun.xml.internal.bind.v2.schemagen.xmlschema.Import;
import java.io.IOException;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Paprifat
 */
public class CashierView extends javax.swing.JFrame {

    Object ob;
    CartList aCartList = new CartList();
    Double total = 0.0;

    /** Creates new form CashierView */
    public CashierView() {
        initComponents();
    }

    /* public CashierView(Object ob) {
    this.ob = ob;
    }*/
    public void setOb(Object ob) {
        this.ob = ob;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        productPanel = new javax.swing.JPanel();
        pNameLabel = new javax.swing.JLabel();
        pSizeLabel = new javax.swing.JLabel();
        discountTextField = new javax.swing.JTextField();
        pQuantityLabel = new javax.swing.JLabel();
        pSizeComboBox = new javax.swing.JComboBox();
        addButton = new javax.swing.JButton();
        cancleButton = new javax.swing.JButton();
        salesmanIdTextField = new javax.swing.JTextField();
        pQuantityLabel1 = new javax.swing.JLabel();
        pQuantityLabel2 = new javax.swing.JLabel();
        pQuantityTextField1 = new javax.swing.JTextField();
        pIdTextField = new javax.swing.JTextField();
        pNameLabel2 = new javax.swing.JLabel();
        pQuantityLabel3 = new javax.swing.JLabel();
        loginInfoPanel = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();
        userNameTextField = new javax.swing.JTextField();
        userIdTextField = new javax.swing.JTextField();
        userIdLabel = new javax.swing.JLabel();
        dateTextField = new javax.swing.JTextField();
        detailsButton = new javax.swing.JButton();
        transcationPanel = new javax.swing.JPanel();
        purchaseButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        transactionScrollPane = new javax.swing.JScrollPane();
        transactionTable = new javax.swing.JTable();
        pNameLabel1 = new javax.swing.JLabel();
        totalTextField = new javax.swing.JTextField();
        pNameLabel3 = new javax.swing.JLabel();
        givenTextField = new javax.swing.JTextField();
        pNameLabel4 = new javax.swing.JLabel();
        returnTextField = new javax.swing.JTextField();
        pNameLabel5 = new javax.swing.JLabel();
        pNameLabel7 = new javax.swing.JLabel();
        pNameLabel8 = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        nameRadioButton = new javax.swing.JRadioButton();
        idRadioButton = new javax.swing.JRadioButton();
        idLabel = new javax.swing.JLabel();
        sizeLabel = new javax.swing.JLabel();
        sizeTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        idSearchButton = new javax.swing.JButton();
        nameSearchButton = new javax.swing.JButton();
        idTextField = new javax.swing.JTextField();
        catagoryRadioButton = new javax.swing.JRadioButton();
        nameLabel1 = new javax.swing.JLabel();
        catagoryTextField = new javax.swing.JTextField();
        nameSearchButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cashier View");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 1, 18), new java.awt.Color(255, 0, 0))); // NOI18N
        productPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pNameLabel.setFont(new java.awt.Font("Segoe Print", 1, 14));
        pNameLabel.setText("By Salesman:");
        productPanel.add(pNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, -1));

        pSizeLabel.setFont(new java.awt.Font("Segoe Print", 1, 14));
        pSizeLabel.setText("Product size:");
        productPanel.add(pSizeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 55, -1, -1));

        discountTextField.setText("0");
        productPanel.add(discountTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 60, 86, -1));

        pQuantityLabel.setFont(new java.awt.Font("Segoe Print", 1, 14));
        pQuantityLabel.setText("Product quantity:");
        productPanel.add(pQuantityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 55, 130, -1));

        pSizeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--select size--", "18", "20", "22", " " }));
        productPanel.add(pSizeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 59, 99, -1));

        addButton.setBackground(new java.awt.Color(102, 153, 255));
        addButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        productPanel.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 100, -1, -1));

        cancleButton.setBackground(new java.awt.Color(102, 153, 255));
        cancleButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        cancleButton.setText("Cancel");
        cancleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleButtonActionPerformed(evt);
            }
        });
        productPanel.add(cancleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 100, -1, -1));
        productPanel.add(salesmanIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 86, -1));

        pQuantityLabel1.setFont(new java.awt.Font("Segoe Print", 1, 14));
        pQuantityLabel1.setText("%");
        productPanel.add(pQuantityLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 60, -1, -1));

        pQuantityLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        pQuantityLabel2.setText("ex:1..n");
        productPanel.add(pQuantityLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, 50, -1));
        productPanel.add(pQuantityTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 59, 86, -1));
        productPanel.add(pIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 59, 86, -1));

        pNameLabel2.setFont(new java.awt.Font("Segoe Print", 1, 14));
        pNameLabel2.setText("Product id:");
        productPanel.add(pNameLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 55, 112, -1));

        pQuantityLabel3.setFont(new java.awt.Font("Segoe Print", 1, 14));
        pQuantityLabel3.setText("Discount:");
        productPanel.add(pQuantityLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 56, 70, 30));

        getContentPane().add(productPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 1010, 133));

        loginInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 1, 18), new java.awt.Color(255, 0, 51))); // NOI18N

        logoutButton.setBackground(new java.awt.Color(102, 153, 255));
        logoutButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        userNameTextField.setEditable(false);
        userNameTextField.setText("user name");
        userNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTextFieldActionPerformed(evt);
            }
        });

        userIdTextField.setEditable(false);
        userIdTextField.setText("user ID");
        userIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIdTextFieldActionPerformed(evt);
            }
        });

        userIdLabel.setText("User ID:");

        dateTextField.setEditable(false);
        dateTextField.setFont(new java.awt.Font("Tahoma", 1, 14));
        dateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextFieldActionPerformed(evt);
            }
        });

        detailsButton.setBackground(new java.awt.Color(102, 153, 255));
        detailsButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        detailsButton.setText("Details");
        detailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginInfoPanelLayout = new javax.swing.GroupLayout(loginInfoPanel);
        loginInfoPanel.setLayout(loginInfoPanelLayout);
        loginInfoPanelLayout.setHorizontalGroup(
            loginInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginInfoPanelLayout.createSequentialGroup()
                .addGroup(loginInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginInfoPanelLayout.createSequentialGroup()
                        .addGroup(loginInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(userNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(logoutButton))
                    .addGroup(loginInfoPanelLayout.createSequentialGroup()
                        .addComponent(userIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(detailsButton)))
                .addContainerGap())
        );
        loginInfoPanelLayout.setVerticalGroup(
            loginInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginInfoPanelLayout.createSequentialGroup()
                .addGroup(loginInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutButton))
                .addGap(18, 18, 18)
                .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loginInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detailsButton)))
        );

        getContentPane().add(loginInfoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1104, 11, -1, -1));

        transcationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Transaction Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 1, 18), new java.awt.Color(255, 0, 0))); // NOI18N

        purchaseButton.setBackground(new java.awt.Color(102, 153, 255));
        purchaseButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        purchaseButton.setText("Purchase");
        purchaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseButtonActionPerformed(evt);
            }
        });

        clearButton.setBackground(new java.awt.Color(102, 153, 255));
        clearButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        transactionTable.setAutoCreateRowSorter(true);
        transactionTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        transactionTable.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14));
        transactionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product id", "Product name", "Product size", "quantity", "Total price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        transactionScrollPane.setViewportView(transactionTable);

        pNameLabel1.setFont(new java.awt.Font("Segoe Print", 1, 14));
        pNameLabel1.setText("Given:");

        totalTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totalTextFieldMouseClicked(evt);
            }
        });

        pNameLabel3.setFont(new java.awt.Font("Segoe Print", 1, 14));
        pNameLabel3.setText("Total:");

        pNameLabel4.setFont(new java.awt.Font("Segoe Print", 1, 14));
        pNameLabel4.setText("Returned:");

        pNameLabel5.setFont(new java.awt.Font("Segoe Print", 1, 14));
        pNameLabel5.setText("Tk.");

        pNameLabel7.setFont(new java.awt.Font("Segoe Print", 1, 14));
        pNameLabel7.setText("Tk.");

        pNameLabel8.setFont(new java.awt.Font("Segoe Print", 1, 14));
        pNameLabel8.setText("Tk.");

        javax.swing.GroupLayout transcationPanelLayout = new javax.swing.GroupLayout(transcationPanel);
        transcationPanel.setLayout(transcationPanelLayout);
        transcationPanelLayout.setHorizontalGroup(
            transcationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transcationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transcationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(transactionScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE)
                    .addGroup(transcationPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(pNameLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(totalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pNameLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(pNameLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(givenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pNameLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(pNameLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(returnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pNameLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                        .addComponent(purchaseButton)
                        .addGap(18, 18, 18)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)))
                .addContainerGap())
        );
        transcationPanelLayout.setVerticalGroup(
            transcationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transcationPanelLayout.createSequentialGroup()
                .addComponent(transactionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(transcationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transcationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(purchaseButton)
                        .addComponent(clearButton))
                    .addGroup(transcationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(totalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pNameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(returnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pNameLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pNameLabel1)
                        .addComponent(givenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pNameLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pNameLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pNameLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );

        getContentPane().add(transcationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 168, -1, -1));

        searchPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 1, 18), new java.awt.Color(255, 0, 51))); // NOI18N
        searchPanel.setRequestFocusEnabled(false);
        searchPanel.setVerifyInputWhenFocusTarget(false);

        buttonGroup1.add(nameRadioButton);
        nameRadioButton.setFont(new java.awt.Font("Segoe Print", 1, 14));
        nameRadioButton.setText("By name");

        buttonGroup1.add(idRadioButton);
        idRadioButton.setFont(new java.awt.Font("Segoe Print", 1, 14));
        idRadioButton.setText("By id");

        idLabel.setFont(new java.awt.Font("Segoe Print", 1, 12));
        idLabel.setText("Enter an id :");

        sizeLabel.setFont(new java.awt.Font("Segoe Print", 1, 12));
        sizeLabel.setText("Enter size :");

        nameLabel.setFont(new java.awt.Font("Segoe Print", 1, 12));
        nameLabel.setText("Enter a name:");

        idSearchButton.setBackground(new java.awt.Color(102, 153, 255));
        idSearchButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        idSearchButton.setText("search");
        idSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idSearchButtonActionPerformed(evt);
            }
        });

        nameSearchButton.setBackground(new java.awt.Color(102, 153, 255));
        nameSearchButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        nameSearchButton.setText("search");
        nameSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameSearchButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(catagoryRadioButton);
        catagoryRadioButton.setFont(new java.awt.Font("Segoe Print", 1, 14));
        catagoryRadioButton.setText("By catagory");

        nameLabel1.setFont(new java.awt.Font("Segoe Print", 1, 12));
        nameLabel1.setText("Enter catagory:");

        nameSearchButton1.setBackground(new java.awt.Color(102, 153, 255));
        nameSearchButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        nameSearchButton1.setText("search");
        nameSearchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameSearchButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameSearchButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idSearchButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idRadioButton)
                    .addComponent(nameRadioButton)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idLabel)
                            .addComponent(sizeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(catagoryRadioButton)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(nameLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(catagoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nameSearchButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(idRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sizeLabel)
                    .addComponent(sizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(nameRadioButton))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idSearchButton)))
                .addGap(18, 18, 18)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(nameSearchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(catagoryRadioButton)
                .addGap(18, 18, 18)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel1)
                    .addComponent(catagoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(nameSearchButton1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(searchPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1102, 168, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 156, 1349, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void userIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIdTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_userIdTextFieldActionPerformed

    private void dateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTextFieldActionPerformed

    private void userNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTextFieldActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        PosLogin aPosLogin = new PosLogin();
        aPosLogin.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void detailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsButtonActionPerformed
        // TODO add your handling code here:
        CurrentUser aCurrentUser = null;
        if (ob != null) {
            aCurrentUser = (CurrentUser) ob;
        }
        userIdTextField.setText(aCurrentUser.getUserId());
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        Date date = new Date();
        dateTextField.setText(dateFormat.format(date));
        userNameTextField.setText(aCurrentUser.getEmployeeName());
    }//GEN-LAST:event_detailsButtonActionPerformed

    private void idSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idSearchButtonActionPerformed
        // TODO add your handling code here:
        String result = null;
        String id = idTextField.getText();
        String size = sizeTextField.getText();
        SearchById aSearchById = new SearchById(id, size);
        try {
            result = aSearchById.GetSearch();
        } catch (SQLException ex) {
            Logger.getLogger(CashierView.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, result);
    }//GEN-LAST:event_idSearchButtonActionPerformed

    private void nameSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameSearchButtonActionPerformed
        // TODO add your handling code here: 
        String result = null;
        SearchByName aSearchByName = new SearchByName(nameTextField.getText());
        try {
            result = aSearchByName.GetSearch();
        } catch (SQLException ex) {
            Logger.getLogger(CashierView.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, result);
    }//GEN-LAST:event_nameSearchButtonActionPerformed

    private void nameSearchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameSearchButton1ActionPerformed
        // TODO add your handling code here:
        String result = null;
        SearchByCategory aSearchByCategory = new SearchByCategory(catagoryTextField.getText());
        try {
            result = aSearchByCategory.GetSearch();
        } catch (SQLException ex) {
            Logger.getLogger(CashierView.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, result);
    }//GEN-LAST:event_nameSearchButton1ActionPerformed

    @SuppressWarnings("unchecked")
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        SelectProduct aSelectProduct = new SelectProduct(pIdTextField.getText(), (String) pSizeComboBox.getSelectedItem(), pQuantityTextField1.getText(), discountTextField.getText(), salesmanIdTextField.getText());
        try {
            aSelectProduct.GetSelectedProduct(aCartList);


        } catch (SQLException ex) {
            Logger.getLogger(CashierView.class.getName()).log(Level.SEVERE, null, ex);
        }

        Vector columns = new Vector(5);
        Vector data = new Vector();

        for (int i = 0; i < 5; i++) {
            columns.add(transactionTable.getColumnName(i));
        }

        Vector row;
        total = 0.0;
        for (Cart aCart : aCartList.getCartList()) {
            row = new Vector(5);
            for (int i = 1; i <= 5; i++) {
                row.add(aCart.getProductId());
                row.add(aCart.getProductName());
                row.add(aCart.getProductSize());
                row.add(aCart.getQuantity());
                row.add(NumberFormat.getInstance().format(aCart.getPrice()));
            }
            total += aCart.getPrice();
            data.add(row);
        }
        DefaultTableModel tableModel = new DefaultTableModel(data, columns);
        transactionTable.setModel(tableModel);

    }//GEN-LAST:event_addButtonActionPerformed

    private void totalTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalTextFieldMouseClicked
        // TODO add your handling code here:

        totalTextField.setText(String.valueOf(NumberFormat.getInstance().format(total)));
    }//GEN-LAST:event_totalTextFieldMouseClicked

    private void purchaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseButtonActionPerformed
        // TODO add your handling code here:
        double given = Double.valueOf(givenTextField.getText());
        double returned = given - total;
        returnTextField.setText(String.valueOf(NumberFormat.getInstance().format(returned)));
        CreateTransaction aCreateTransaction = new CreateTransaction(total,given,returned);
        
        try {
            try {
                aCreateTransaction.MakeTransaction(aCartList);
                JOptionPane.showMessageDialog(null,"Transaction Succuessfully Done"+"\n"+"Check The Reciept.");
            } catch (IOException ex) {
                Logger.getLogger(CashierView.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CashierView.class.getName()).log(Level.SEVERE, null, ex);
        }
     
    }//GEN-LAST:event_purchaseButtonActionPerformed

    private void cancleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleButtonActionPerformed
        // TODO add your handling code here:
        pIdTextField.setText(null);
        pQuantityTextField1.setText(null);
        salesmanIdTextField.setText(null);
        discountTextField.setText(null);
    }//GEN-LAST:event_cancleButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        aCartList.getCartList().clear();
        Vector columns = new Vector(5);
        Vector data = new Vector();

        for (int i = 0; i < 5; i++) {
            columns.add(transactionTable.getColumnName(i));
        }

        DefaultTableModel tableModel = new DefaultTableModel(data, columns);
        tableModel.setRowCount(0);
        transactionTable.setModel(tableModel);

    }//GEN-LAST:event_clearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CashierView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancleButton;
    private javax.swing.JRadioButton catagoryRadioButton;
    private javax.swing.JTextField catagoryTextField;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JButton detailsButton;
    private javax.swing.JTextField discountTextField;
    private javax.swing.JTextField givenTextField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JRadioButton idRadioButton;
    private javax.swing.JButton idSearchButton;
    private javax.swing.JTextField idTextField;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel loginInfoPanel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JRadioButton nameRadioButton;
    private javax.swing.JButton nameSearchButton;
    private javax.swing.JButton nameSearchButton1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField pIdTextField;
    private javax.swing.JLabel pNameLabel;
    private javax.swing.JLabel pNameLabel1;
    private javax.swing.JLabel pNameLabel2;
    private javax.swing.JLabel pNameLabel3;
    private javax.swing.JLabel pNameLabel4;
    private javax.swing.JLabel pNameLabel5;
    private javax.swing.JLabel pNameLabel7;
    private javax.swing.JLabel pNameLabel8;
    private javax.swing.JLabel pQuantityLabel;
    private javax.swing.JLabel pQuantityLabel1;
    private javax.swing.JLabel pQuantityLabel2;
    private javax.swing.JLabel pQuantityLabel3;
    private javax.swing.JTextField pQuantityTextField1;
    private javax.swing.JComboBox pSizeComboBox;
    private javax.swing.JLabel pSizeLabel;
    private javax.swing.JPanel productPanel;
    private javax.swing.JButton purchaseButton;
    private javax.swing.JTextField returnTextField;
    private javax.swing.JTextField salesmanIdTextField;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JLabel sizeLabel;
    private javax.swing.JTextField sizeTextField;
    private javax.swing.JTextField totalTextField;
    private javax.swing.JScrollPane transactionScrollPane;
    private javax.swing.JTable transactionTable;
    private javax.swing.JPanel transcationPanel;
    private javax.swing.JLabel userIdLabel;
    private javax.swing.JTextField userIdTextField;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
}
