/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EmployeeDetails.java
 *
 * Created on Jan 6, 2013, 6:33:30 AM
 */
package batapos;

import Manager.Employee;
import Manager.EmployeeList;
import Manager.EmployeeTable;
import Manager.Supplier;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asadul
 */
public class EmployeeDetails extends javax.swing.JFrame {

    /** Creates new form EmployeeDetails */
    public EmployeeDetails() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        employeeHeadLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeeInformationTable = new javax.swing.JTable();
        homeButton = new javax.swing.JButton();
        showButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Details");

        employeeHeadLabel.setFont(new java.awt.Font("Segoe Print", 1, 24));
        employeeHeadLabel.setForeground(new java.awt.Color(102, 153, 255));
        employeeHeadLabel.setText("Employee Information");

        employeeInformationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee id", "Employee name", "Designation", "Address", "Contact", "E-mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(employeeInformationTable);

        homeButton.setBackground(new java.awt.Color(51, 102, 255));
        homeButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        showButton.setBackground(new java.awt.Color(102, 153, 255));
        showButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        showButton.setText("Show");
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(348, 348, 348)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(employeeHeadLabel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(showButton)
                            .addGap(35, 35, 35)
                            .addComponent(homeButton))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(405, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(employeeHeadLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeButton)
                    .addComponent(showButton))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtonActionPerformed
        // TODO add your handling code here:
        Object ob;
        EmployeeList aEmployeeList= null;
        EmployeeTable aEmployeeTable = new EmployeeTable();
        try {
            aEmployeeTable.GetEmployeeTable();
        } catch (SQLException ex) {
            Logger.getLogger(SupplierDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        ob = aEmployeeTable.GetEmployeelist();
        if(ob!=null){
            aEmployeeList=(EmployeeList)ob;
        }
        Vector columns = new Vector(6);
        Vector data = new Vector();

        for (int i = 0; i < 6; i++) {
            columns.add(employeeInformationTable.getColumnName(i));
        }
        Vector row;
        for(Employee aEmployee : aEmployeeList.getEmployeeList()){
            row = new Vector(6);
            for (int i = 1; i <= 6; i++) {
                row.add(aEmployee.getEmployeeid());
                row.add(aEmployee.getEmployeeName());
                row.add(aEmployee.getDesignation());
                row.add(aEmployee.getAddress());
                row.add(aEmployee.getContact());
                row.add(aEmployee.getEmail());
            }
            data.add(row);
            
        }
        DefaultTableModel tableModel = new DefaultTableModel(data, columns);
        employeeInformationTable.setModel(tableModel);
    }//GEN-LAST:event_showButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        ManagerView aManagerView =new ManagerView();
        this.setVisible(false);
        aManagerView.setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new EmployeeDetails().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel employeeHeadLabel;
    private javax.swing.JTable employeeInformationTable;
    private javax.swing.JButton homeButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton showButton;
    // End of variables declaration//GEN-END:variables
}
