/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ManagerView.java
 *
 * Created on Jan 4, 2013, 2:44:17 AM
 */
package batapos;

import Login.CurrentUser;

/**
 *
 * @author Paprifat
 */
public class ManagerView extends javax.swing.JFrame {
    CurrentUser ob;
    /** Creates new form ManagerView */
    public ManagerView() {
        initComponents();
    }

    public void setOb(CurrentUser ob) {
        this.ob = ob;
    }

   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        posLabel = new javax.swing.JLabel();
        managerMenuBar = new javax.swing.JMenuBar();
        accountMenu = new javax.swing.JMenu();
        aDetailsMenuItem = new javax.swing.JMenuItem();
        logoutMenuItem = new javax.swing.JMenuItem();
        inventoryMenu = new javax.swing.JMenu();
        iViewMenuItem = new javax.swing.JMenuItem();
        updateMenuItem = new javax.swing.JMenuItem();
        supplierMenu = new javax.swing.JMenu();
        sDetailsMenuItem = new javax.swing.JMenuItem();
        sUpdateMenuItem = new javax.swing.JMenuItem();
        orderMenu = new javax.swing.JMenu();
        oDetailsMenuItem = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        employeeMenu = new javax.swing.JMenu();
        eDetailsMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        salesmanViewMenuItem = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        transactionMenu = new javax.swing.JMenu();
        detailsMenuItem = new javax.swing.JMenuItem();
        specificDetailMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manager View");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/batapos/bataLogo.jpg"))); // NOI18N

        posLabel.setFont(new java.awt.Font("Script MT Bold", 3, 48));
        posLabel.setText("  Point Of Sale Manager Account");
        posLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 3, true));

        accountMenu.setBackground(new java.awt.Color(204, 204, 204));
        accountMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        accountMenu.setText("  Account info  ");

        aDetailsMenuItem.setText("Details");
        aDetailsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aDetailsMenuItemActionPerformed(evt);
            }
        });
        accountMenu.add(aDetailsMenuItem);

        logoutMenuItem.setText("Logout");
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        accountMenu.add(logoutMenuItem);

        managerMenuBar.add(accountMenu);

        inventoryMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        inventoryMenu.setText("  Inventory   ");

        iViewMenuItem.setText("View");
        iViewMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iViewMenuItemActionPerformed(evt);
            }
        });
        inventoryMenu.add(iViewMenuItem);

        updateMenuItem.setText("Update");
        updateMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMenuItemActionPerformed(evt);
            }
        });
        inventoryMenu.add(updateMenuItem);

        managerMenuBar.add(inventoryMenu);

        supplierMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        supplierMenu.setText("  Supplier info  ");

        sDetailsMenuItem.setText("details");
        sDetailsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sDetailsMenuItemActionPerformed(evt);
            }
        });
        supplierMenu.add(sDetailsMenuItem);

        sUpdateMenuItem.setText("Update");
        sUpdateMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sUpdateMenuItemActionPerformed(evt);
            }
        });
        supplierMenu.add(sUpdateMenuItem);

        managerMenuBar.add(supplierMenu);

        orderMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        orderMenu.setText("  Order   ");

        oDetailsMenuItem.setText("details");
        oDetailsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oDetailsMenuItemActionPerformed(evt);
            }
        });
        orderMenu.add(oDetailsMenuItem);

        jMenuItem9.setText("new order");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        orderMenu.add(jMenuItem9);

        managerMenuBar.add(orderMenu);

        employeeMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        employeeMenu.setText("  Employee info   ");

        eDetailsMenuItem.setText("Details");
        eDetailsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eDetailsMenuItemActionPerformed(evt);
            }
        });
        employeeMenu.add(eDetailsMenuItem);

        managerMenuBar.add(employeeMenu);

        jMenu1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setText("  product   ");

        jMenuItem2.setText("Details");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem5.setText("Add Product");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        managerMenuBar.add(jMenu1);

        jMenu2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu2.setText("Salesman Info");

        salesmanViewMenuItem.setText("Details");
        salesmanViewMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesmanViewMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(salesmanViewMenuItem);

        jMenuItem4.setText("Set target");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        managerMenuBar.add(jMenu2);

        transactionMenu.setBackground(new java.awt.Color(204, 204, 204));
        transactionMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        transactionMenu.setText("  Transaction info   ");

        detailsMenuItem.setText("details");
        detailsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsMenuItemActionPerformed(evt);
            }
        });
        transactionMenu.add(detailsMenuItem);

        specificDetailMenuItem.setText("Specific detail");
        specificDetailMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specificDetailMenuItemActionPerformed(evt);
            }
        });
        transactionMenu.add(specificDetailMenuItem);

        managerMenuBar.add(transactionMenu);

        setJMenuBar(managerMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(343, Short.MAX_VALUE)
                .addComponent(posLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(posLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(318, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aDetailsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aDetailsMenuItemActionPerformed
        // TODO add your handling code here:
        CurrentUser aCurrentUser =null;
        if(ob!=null){
            aCurrentUser=(CurrentUser)ob;
        }
        AccountInfo accountInfo = new AccountInfo();
        accountInfo.setOb(aCurrentUser);
        this.setVisible(false);
        accountInfo.setVisible(true);
        
    }//GEN-LAST:event_aDetailsMenuItemActionPerformed

    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
        // TODO add your handling code here:
        PosLogin aPosLogin =new PosLogin();
        this.setVisible(false);
        aPosLogin.setVisible(true);
    }//GEN-LAST:event_logoutMenuItemActionPerformed

    private void iViewMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iViewMenuItemActionPerformed
        // TODO add your handling code here:
        ViewInventory aViewInventory = new ViewInventory();
        this.setVisible(false);
        aViewInventory.setVisible(true);
    }//GEN-LAST:event_iViewMenuItemActionPerformed

    private void updateMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMenuItemActionPerformed
        // TODO add your handling code here:
        UpdateInventory aUpdateInventory = new UpdateInventory();
        this.setVisible(false);
        aUpdateInventory.setVisible(true);
                
    }//GEN-LAST:event_updateMenuItemActionPerformed

    private void sDetailsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sDetailsMenuItemActionPerformed
        // TODO add your handling code here:
        SupplierDetails aSupplierDetails = new SupplierDetails();
        this.setVisible(false);
        aSupplierDetails.setVisible(true);
    }//GEN-LAST:event_sDetailsMenuItemActionPerformed

    private void sUpdateMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sUpdateMenuItemActionPerformed
        // TODO add your handling code here:
        SupplierUpdate aSupplierUpdate = new SupplierUpdate();
        this.setVisible(false);
        aSupplierUpdate.setVisible(true);
    }//GEN-LAST:event_sUpdateMenuItemActionPerformed

    private void detailsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsMenuItemActionPerformed
        // TODO add your handling code here:
        TransactionDetails aTransactionDetails = new TransactionDetails();
        this.setVisible(false);
        aTransactionDetails.setVisible(true);
    }//GEN-LAST:event_detailsMenuItemActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        NewOrder aNewOrder = new NewOrder();
        this.setVisible(false);
        aNewOrder.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void oDetailsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oDetailsMenuItemActionPerformed
        // TODO add your handling code here:
        OrderDetails aOrderDetails =new OrderDetails();
        this.setVisible(false);
        aOrderDetails.setVisible(true);
    }//GEN-LAST:event_oDetailsMenuItemActionPerformed

    private void eDetailsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eDetailsMenuItemActionPerformed
        // TODO add your handling code here:
        EmployeeDetails aEmployeeDetails = new EmployeeDetails();
        this.setVisible(false);
        aEmployeeDetails.setVisible(true);
    }//GEN-LAST:event_eDetailsMenuItemActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        ProductDetails aProductDetails = new ProductDetails();
        this.setVisible(false);
        aProductDetails.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        ProductUpdate aProductUpdate = new ProductUpdate();
        this.setVisible(false);
        aProductUpdate.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void salesmanViewMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesmanViewMenuItemActionPerformed
        // TODO add your handling code here:
        SalesmanDetails aSalesmanDetails = new SalesmanDetails();
        this.setVisible(false);
        aSalesmanDetails.setVisible(true);
    }//GEN-LAST:event_salesmanViewMenuItemActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        UpdateTarget aUpdateTarget =new UpdateTarget();
        this.setVisible(false);
        aUpdateTarget.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void specificDetailMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specificDetailMenuItemActionPerformed
        // TODO add your handling code here:
        MoreTransactionDetails aMoreTransactionDetails = new MoreTransactionDetails();
        this.setVisible(false);
        aMoreTransactionDetails.setVisible(true);
    }//GEN-LAST:event_specificDetailMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ManagerView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aDetailsMenuItem;
    private javax.swing.JMenu accountMenu;
    private javax.swing.JMenuItem detailsMenuItem;
    private javax.swing.JMenuItem eDetailsMenuItem;
    private javax.swing.JMenu employeeMenu;
    private javax.swing.JMenuItem iViewMenuItem;
    private javax.swing.JMenu inventoryMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JMenuBar managerMenuBar;
    private javax.swing.JMenuItem oDetailsMenuItem;
    private javax.swing.JMenu orderMenu;
    private javax.swing.JLabel posLabel;
    private javax.swing.JMenuItem sDetailsMenuItem;
    private javax.swing.JMenuItem sUpdateMenuItem;
    private javax.swing.JMenuItem salesmanViewMenuItem;
    private javax.swing.JMenuItem specificDetailMenuItem;
    private javax.swing.JMenu supplierMenu;
    private javax.swing.JMenu transactionMenu;
    private javax.swing.JMenuItem updateMenuItem;
    // End of variables declaration//GEN-END:variables
}
