/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewOrder.java
 *
 * Created on Jan 6, 2013, 4:34:43 PM
 */
package batapos;

import Manager.MakeOrder;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author saif
 */
public class NewOrder extends javax.swing.JFrame {

    /** Creates new form NewOrder */
    public NewOrder() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pIdTextField = new javax.swing.JTextField();
        quantityTextField = new javax.swing.JTextField();
        homeCancleButton = new javax.swing.JButton();
        orderSendButton = new javax.swing.JButton();
        sIdTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dDateTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pSizeTextField = new javax.swing.JTextField();
        clearCancleButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New Order");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "oder details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 1, 24), new java.awt.Color(255, 0, 51))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 14));
        jLabel1.setText("Product id:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 94, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 14));
        jLabel3.setText("Quantity :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));
        jPanel1.add(pIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 59, -1));
        jPanel1.add(quantityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 59, -1));

        homeCancleButton.setText("Home");
        homeCancleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeCancleButtonActionPerformed(evt);
            }
        });
        jPanel1.add(homeCancleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, 30));

        orderSendButton.setText("Send order");
        orderSendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderSendButtonActionPerformed(evt);
            }
        });
        jPanel1.add(orderSendButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, 30));
        jPanel1.add(sIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 59, 20));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 14));
        jLabel4.setText("Supplier id:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 14));
        jLabel6.setText("Delivary date :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));
        jPanel1.add(dDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 110, -1));

        jLabel7.setText("ex : YY-MM-DD");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe Print", 1, 14));
        jLabel8.setText("Product size :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));
        jPanel1.add(pSizeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 59, -1));

        clearCancleButton.setText("Clear");
        clearCancleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearCancleButtonActionPerformed(evt);
            }
        });
        jPanel1.add(clearCancleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 580, 190));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 24));
        jLabel5.setText("Give Order");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 140, 20));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1356)/2, (screenSize.height-709)/2, 1356, 709);
    }// </editor-fold>//GEN-END:initComponents

    private void orderSendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderSendButtonActionPerformed
        // TODO add your handling code here:
        String id =pIdTextField.getText();
        String size = pSizeTextField.getText();
        String productId = id+size;
        int quantity = Integer.parseInt(quantityTextField.getText());
        int supplierId = Integer.parseInt(sIdTextField.getText());
        String delivaryDate = dDateTextField.getText();
        MakeOrder aMakeOrder = new MakeOrder();
        try {
            if(aMakeOrder.Sendorder(productId, quantity, supplierId, delivaryDate)){
                JOptionPane.showMessageDialog(null, "Order has been sent to supplier");
            }
            else
                JOptionPane.showMessageDialog(null, "There are some problems");
        } catch (SQLException ex) {
            Logger.getLogger(NewOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_orderSendButtonActionPerformed

    private void clearCancleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearCancleButtonActionPerformed
        // TODO add your handling code here:
        pIdTextField.setText(null);
        pSizeTextField.setText(null);
        quantityTextField.setText(null);
        sIdTextField.setText(null);
        dDateTextField.setText(null);
    }//GEN-LAST:event_clearCancleButtonActionPerformed

    private void homeCancleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeCancleButtonActionPerformed
        // TODO add your handling code here:
        ManagerView aManagerView = new ManagerView();
        this.setVisible(false);
        aManagerView.setVisible(true);
    }//GEN-LAST:event_homeCancleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewOrder().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearCancleButton;
    private javax.swing.JTextField dDateTextField;
    private javax.swing.JButton homeCancleButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton orderSendButton;
    private javax.swing.JTextField pIdTextField;
    private javax.swing.JTextField pSizeTextField;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JTextField sIdTextField;
    // End of variables declaration//GEN-END:variables
}
