/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PosLogin.java
 *
 * Created on Dec 30, 2012, 9:33:05 PM
 */
package batapos;

import Login.Login;
import Login.User;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 2A
 */
public class PosLogin extends javax.swing.JFrame {

    /** Creates new form PosLogin */
    public PosLogin() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bataLabel = new javax.swing.JLabel();
        posLabel = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        passWordLabel = new javax.swing.JLabel();
        userLabel1 = new javax.swing.JLabel();
        userTextField = new javax.swing.JTextField();
        PassWordField = new javax.swing.JPasswordField();
        clearButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bataLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/batapos/bataLogo.jpg"))); // NOI18N
        getContentPane().add(bataLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1320, 260));

        posLabel.setFont(new java.awt.Font("Script MT Bold", 3, 48));
        posLabel.setText("  Point Of Sale");
        posLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 3, true));
        getContentPane().add(posLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 380, 80));

        loginPanel.setBackground(new java.awt.Color(255, 204, 204));
        loginPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Login Panel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB", 0, 18), new java.awt.Color(255, 51, 0))); // NOI18N
        loginPanel.setForeground(new java.awt.Color(255, 0, 51));
        loginPanel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18));
        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passWordLabel.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24));
        passWordLabel.setText("Password:");
        loginPanel.add(passWordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 110, 31));

        userLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24));
        userLabel1.setText("User name:");
        loginPanel.add(userLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 130, 31));
        loginPanel.add(userTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 150, -1));
        loginPanel.add(PassWordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 150, -1));

        clearButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        clearButton.setForeground(new java.awt.Color(51, 102, 255));
        clearButton.setText("clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        loginPanel.add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 70, -1));

        loginButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        loginButton.setForeground(new java.awt.Color(51, 102, 255));
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginPanel.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 70, -1));

        getContentPane().add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 370, 220));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1356)/2, (screenSize.height-709)/2, 1356, 709);
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        String userName = userTextField.getText();
        String password = PassWordField.getText();

        Login aLogin = new Login(userName, password);
        try {
            if (aLogin.CheckUser().equals("cashier")) {
                JOptionPane.showMessageDialog(null, "Wellcome To Cashier View");
                this.setVisible(false);
                CashierView aCashierView = new CashierView();
                aCashierView.setOb(aLogin.getOb());
                aCashierView.setVisible(true);

            } else if (aLogin.CheckUser().equals("manager")) {
                JOptionPane.showMessageDialog(null, "Wellcome Manager");
                ManagerView aManagerView =new  ManagerView();
                aManagerView.setOb(aLogin.getOb());
                this.setVisible(false);
                aManagerView.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "You have entered wrong password or user id");
            }
        } catch (SQLException ex) {
            Logger.getLogger(PosLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        userTextField.setText(null);
        PassWordField.setText(null);
    }//GEN-LAST:event_clearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PosLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PosLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PosLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PosLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PosLogin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PassWordField;
    private javax.swing.JLabel bataLabel;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel passWordLabel;
    private javax.swing.JLabel posLabel;
    private javax.swing.JLabel userLabel1;
    private javax.swing.JTextField userTextField;
    // End of variables declaration//GEN-END:variables
}
