/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SupplierUpdate.java
 *
 * Created on Jan 6, 2013, 7:57:16 AM
 */
package batapos;

import Manager.AddSupplier;
import Manager.RemoveSupplier;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Asadul
 */
public class SupplierUpdate extends javax.swing.JFrame {

    /** Creates new form SupplierUpdate */
    public SupplierUpdate() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sNameTextField = new javax.swing.JTextField();
        sContactTextField = new javax.swing.JTextField();
        sBackButton = new javax.swing.JButton();
        sAddButton = new javax.swing.JButton();
        sCancleButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        sIdTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sAddButton1 = new javax.swing.JButton();
        sCancleButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        sEmailTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add/Remove Supplier");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Supplier Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 1, 24), new java.awt.Color(255, 0, 51))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 14));
        jLabel1.setText("Supplier name:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 110, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 14));
        jLabel3.setText("Supplier contact:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));
        jPanel1.add(sNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 170, -1));
        jPanel1.add(sContactTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 170, -1));

        sBackButton.setBackground(new java.awt.Color(102, 153, 255));
        sBackButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        sBackButton.setText("Back");
        sBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sBackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(sBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, -1));

        sAddButton.setBackground(new java.awt.Color(102, 153, 255));
        sAddButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        sAddButton.setText("Remove");
        sAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sAddButtonActionPerformed(evt);
            }
        });
        jPanel1.add(sAddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        sCancleButton1.setBackground(new java.awt.Color(102, 153, 255));
        sCancleButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        sCancleButton1.setText("Clear");
        sCancleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sCancleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(sCancleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 390, 10));
        jPanel1.add(sIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 120, -1));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 14));
        jLabel2.setText("Supplier Id:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 110, -1));

        sAddButton1.setBackground(new java.awt.Color(102, 153, 255));
        sAddButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        sAddButton1.setText("Add");
        sAddButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sAddButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(sAddButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        sCancleButton2.setBackground(new java.awt.Color(102, 153, 255));
        sCancleButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        sCancleButton2.setText("Clear");
        sCancleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sCancleButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(sCancleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 14));
        jLabel4.setText("Supplier E-mail:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));
        jPanel1.add(sEmailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 170, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 24));
        jLabel5.setText("Add/Remove Supplier");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(438, 438, 438)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addGap(79, 79, 79))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(476, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addGap(251, 251, 251))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1356)/2, (screenSize.height-709)/2, 1356, 709);
    }// </editor-fold>//GEN-END:initComponents

    private void sCancleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sCancleButton2ActionPerformed
        // TODO add your handling code here:
        sNameTextField.setText(null);
        sContactTextField.setText(null);
        sEmailTextField.setText(null);
    }//GEN-LAST:event_sCancleButton2ActionPerformed

    private void sAddButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sAddButton1ActionPerformed
        // TODO add your handling code here:
        String name=sNameTextField.getText();
        String contact = sContactTextField.getText();
        String email = sEmailTextField.getText();
        if(!name.equals(null) && !contact.equals(null) && !email.equals(null)){
            AddSupplier aAddSupplier = new AddSupplier();
            try {
                if (aAddSupplier.AddNewSupplier(name, contact, email)){
                    JOptionPane.showMessageDialog(null, "New supplier added successfully");
                }
            } catch (SQLException ex) {
                Logger.getLogger(SupplierUpdate.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Enter the supplier info!!!");
    }//GEN-LAST:event_sAddButton1ActionPerformed

    private void sCancleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sCancleButton1ActionPerformed
        // TODO add your handling code here:
        sIdTextField.setText(null);
    }//GEN-LAST:event_sCancleButton1ActionPerformed

    private void sBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sBackButtonActionPerformed
        // TODO add your handling code here:
        ManagerView aManagerView = new ManagerView();
        this.setVisible(false);
        aManagerView.setVisible(true);
    }//GEN-LAST:event_sBackButtonActionPerformed

    private void sAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sAddButtonActionPerformed
        // TODO add your handling code here:
       String id= sIdTextField.getText();
       if(!id.equals(null)){
           RemoveSupplier aRemoveSupplier =new RemoveSupplier();
            try {
                if(aRemoveSupplier.SupplierRemove(Integer.parseInt(id))){
                    JOptionPane.showMessageDialog(null, "Supplier removed successfulyy!!!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(SupplierUpdate.class.getName()).log(Level.SEVERE, null, ex);
            }
       }
       else
           JOptionPane.showMessageDialog(null, "enter the supplier id");
    }//GEN-LAST:event_sAddButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupplierUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupplierUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupplierUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupplierUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SupplierUpdate().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton sAddButton;
    private javax.swing.JButton sAddButton1;
    private javax.swing.JButton sBackButton;
    private javax.swing.JButton sCancleButton1;
    private javax.swing.JButton sCancleButton2;
    private javax.swing.JTextField sContactTextField;
    private javax.swing.JTextField sEmailTextField;
    private javax.swing.JTextField sIdTextField;
    private javax.swing.JTextField sNameTextField;
    // End of variables declaration//GEN-END:variables
}
