/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UpdateTarget.java
 *
 * Created on Jan 27, 2013, 2:30:56 AM
 */
package batapos;

import Manager.TargetUpdate;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Kaiser
 */
public class UpdateTarget extends javax.swing.JFrame {

    /** Creates new form UpdateTarget */
    public UpdateTarget() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        eIdTextField = new javax.swing.JTextField();
        targetTextField = new javax.swing.JTextField();
        sBackButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        sAddButton1 = new javax.swing.JButton();
        CancleButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Update Target");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 24));
        jLabel5.setText("Update Target");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Update details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 1, 24), new java.awt.Color(255, 0, 51))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 14));
        jLabel1.setText("Employee id:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 110, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 14));
        jLabel3.setText("Tk.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));
        jPanel1.add(eIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 120, -1));
        jPanel1.add(targetTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 120, -1));

        sBackButton.setBackground(new java.awt.Color(102, 153, 255));
        sBackButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        sBackButton.setText("Back");
        sBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sBackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(sBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 390, 10));

        sAddButton1.setBackground(new java.awt.Color(102, 153, 255));
        sAddButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        sAddButton1.setText("Add");
        sAddButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sAddButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(sAddButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        CancleButton.setBackground(new java.awt.Color(102, 153, 255));
        CancleButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        CancleButton.setText("Clear");
        CancleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancleButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CancleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 14));
        jLabel4.setText("New target:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(547, 547, 547)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(413, 413, 413)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(501, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(282, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Update target");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sBackButtonActionPerformed
        ManagerView aManagerView =new ManagerView();
        this.setVisible(false);
        aManagerView.setVisible(true);
        // TODO add your handling code here:         ManagerView aManagerView = new ManagerView();         this.setVisible(false);         aManagerView.setVisible(true);     }//GEN-LAST:event_sBackButtonActionPerformed
    }
        private void sAddButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sAddButton1ActionPerformed
             int id =Integer.parseInt( eIdTextField.getText());
             Double target =Double.valueOf( targetTextField.getText());
             TargetUpdate aTargetUpdate = new TargetUpdate();
        
            try {
                if(aTargetUpdate.SetNewTarget(id, target)){
                    JOptionPane.showMessageDialog(null, "New target has been set!!!");
                }
            // TODO add your handling code here:         String id = iIdTextField.getText();         String quantity = quantityTextField.getText();         if (!id.equals(null) && !quantity.equals(null)) {             InventoryChange aInventoryChange = new InventoryChange(id, quantity);             try {                 if (aInventoryChange.UpdateInventory()) {                     JOptionPane.showMessageDialog(null, "Inventory successfully updated!!");                 }             } catch (SQLException ex) {                 Logger.getLogger(UpdateInventory.class.getName()).log(Level.SEVERE, null, ex);             }         } else {             JOptionPane.showMessageDialog(null, "please Fill up the boxes");         }     }
            } catch (SQLException ex) {
                Logger.getLogger(UpdateTarget.class.getName()).log(Level.SEVERE, null, ex);
            }
        // TODO add your handling code here:         String id = iIdTextField.getText();         String quantity = quantityTextField.getText();         if (!id.equals(null) && !quantity.equals(null)) {             InventoryChange aInventoryChange = new InventoryChange(id, quantity);             try {                 if (aInventoryChange.UpdateInventory()) {                     JOptionPane.showMessageDialog(null, "Inventory successfully updated!!");                 }             } catch (SQLException ex) {                 Logger.getLogger(UpdateInventory.class.getName()).log(Level.SEVERE, null, ex);             }         } else {             JOptionPane.showMessageDialog(null, "please Fill up the boxes");         }     }//GEN-LAST:event_sAddButton1ActionPerformed
        }
        private void CancleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancleButtonActionPerformed
            eIdTextField.setText(null);
            targetTextField.setText(null);
        // TODO add your handling code here:         iIdTextField.setText(null);         quantityTextField.setText(null);     }//GEN-LAST:event_CancleButtonActionPerformed
        }  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateTarget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateTarget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateTarget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateTarget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new UpdateTarget().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancleButton;
    private javax.swing.JTextField eIdTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton sAddButton1;
    private javax.swing.JButton sBackButton;
    private javax.swing.JTextField targetTextField;
    // End of variables declaration//GEN-END:variables
}
